apiVersion: v1
kind: Template
metadata:
  name: s2i-thoth-example
  annotations:
    openshift.io/display-name: "Thoth S2I Example"
    openshift.io/documentation-url: "https://github.com/thoth-station/s2i-thoth-example"
    openshift.io/provider-display-name: "Red Hat, Inc."
    description: |-
      An example application integrating OpenShift's s2i with Thoth's recommendation engine.
    version: 0.2.0
    tags: thoth,openshift,s2i,python
    iconClass: icon-python
  labels:
    template: s2i-thoth
    app: "s2i-thoth-example"

parameters:
  - description: "Thoth Environment to use for retrieving advices."
    displayName: "Environment"
    name: "THOTH_ENVIRONMENT_NAME"
    required: true
    value: "test"

objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "s2i-thoth-example"
      labels:
        app: "s2i-thoth-example"
    spec:
      successfulBuildsHistoryLimit: 1
      failedBuildsHistoryLimit: 2
      resources:
        requests:
          cpu: 1
          memory: 512Mi
        limits:
          cpu: 1
          memory: 512Mi
      output:
        to:
          kind: ImageStreamTag
          name: "s2i-thoth-example:latest"
      source:
        type: Git
        git:
          uri: "https://github.com/thoth-station/s2i-thoth"
          ref: "master"
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: "s2i-thoth-python-36:latest"
          env:
            - name: "ENABLE_PIPENV"
              value: "1"
            - name: "WEB_CONCURRENCY"
              value: "4"
            - name: "THAMOS_NO_PROGRESSBAR"
              value: "1"
            - name: "THOTH_ENVIRONMENT_NAME"
              value: "${THOTH_ENVIRONMENT_NAME}"
      triggers:
        - type: ImageChange
          imageChange: {}

  - kind: Route
    apiVersion: v1
    metadata:
      name: "s2i-thoth-example"
      labels:
        app: "s2i-thoth-example"
    spec:
      to:
        kind: Service
        name: "s2i-thoth-example"

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: "s2i-thoth-example"
        service: s2i-thoth
      name: "s2i-thoth-example"
    spec:
      ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
      selector:
        service: s2i-thoth

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      labels:
        app: "s2i-thoth-example"
      name: "s2i-thoth-example"
    spec:
      replicas: 1
      selector:
        service: s2i-thoth
      template:
        metadata:
          labels:
            service: s2i-thoth
        spec:
          containers:
            - name: "s2i-thoth-example"
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  memory: 512Mi
                  cpu: 250m
                limits:
                  memory: 512Mi
                  cpu: 500m
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - s2i-thoth
            from:
              kind: ImageStreamTag
              name: s2i-thoth-example:latest

  - apiVersion: "image.openshift.io/v1"
    kind: ImageStream
    metadata:
      labels:
        app: "s2i-thoth-example"
      name: "s2i-thoth-example"
    spec:
      name: "s2i-thoth-example"

  - apiVersion: "image.openshift.io/v1"
    kind: ImageStream
    metadata:
      labels:
        app: "s2i-thoth-example"
      name: "s2i-thoth-python-36"
    spec:
      tags:
        - name: "latest"
          from:
            kind: "DockerImage"
            name: "registry.access.redhat.com/ubi8/python-36"
          referencePolicy:
            type: "Source"
